apiVersion: v1
kind: Service
metadata:
  name: gcp-cicd-web-app-python-service
spec:
  selector:
    app: gcp-cicd-web-app-python
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer